set(SENSORS -DUSE_ENCS -DUSE_IMU) #-DUSE_IMU -DUSE_ENCS

set(ODOM -DODOM_ENCS -DODOM_IMU -DKF_VERSION=1 -DKF_IMU)

set(DEBUG_OPTS -DDEBUG_IMU_CALIB) #-DDEBUG_PRINTF -DDEBUG_ODOM -DDEBUG_IMU_CALIB -DDEBUG_KF_MATRIXES -DDEBUG_KF_OBS

set(COMMON_VARS -DSYNCHRONIZATION_CYCLES=10)
