
SENSORS += -DUSE_IMU
SENSORS += -DUSE_ENCS

#DEBUG_OPTS += -DDEBUG_PRINTF		#use cutecom, no packet handling
DEBUG_OPTS += -DDEBUG_ODOM
DEBUG_OPTS += -DDEBUG_IMU_CALIB

COMMON_VARS += -DSYNCHRONIZATION_CYCLES=10
