INCLUDE_DIRS = -I../src/common -I../src/host/

CC = gcc
CCOPTS = -Wall -Ofast -std=gnu99 -Wstrict-prototypes $(INCLUDE_DIRS)

HEADERS = serial.h serial_packets.h
OBJS = serial.o serial_packets.o
BINS = host

.phony: clean all

all: $(BINS)

%.o : ../src/common/%.c
	$(CC) $(CCOPTS) -c -o $@  $<

%.o : ../src/host/%.c
	$(CC) $(CCOPTS) -c -o $@  $<


host: ../src/host/host.c $(OBJS)
	$(CC) $(CCOPTS) -o $@ $^ $(LIBS)

clean:
	rm -rf *~  $(BINS) $(OBJS)
